// export * from 'app/my-assets/assets/assets.component';
export * from "app/my-assets/assets/assets.route";
export * from "app/my-assets/my-assets.component";
export * from "app/my-assets/my-assets.route";
export * from "app/my-assets/mutual-fund/mutual-fund.component";
export * from "app/my-assets/mutual-fund/mutual-fund.route";
export * from "app/my-assets/my-assets.route";
export * from "app/my-assets/assets/mutual-fund.service";
export * from "app/my-assets/my-assets.module";
// export * from 'app/my-assets/assets/assets.service';
export * from "app/my-assets/liabilities/liabilities.component";
export * from "app/my-assets/liabilities/liabilities.route";
